import{a as L,s as O,i as f}from"./assets/vendor-CqsEcRFW.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const o of r.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&l(o)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const P="34523545-f21683fd59bfc3e4e2549fe07",R="https://pixabay.com/api";L.defaults.baseURL=R;async function v(a,e,s=1){const l={key:P,q:a,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:e,page:s};return L.get("/",{params:l})}function b(a){return a.hits.map(s=>{const{webformatURL:l,largeImageURL:t,tags:r,likes:o,views:q,comments:M,downloads:H}=s;return`
        <li class="gallery-item">
            <a href="${t}" target="_blank">
                <div class="img-wrapper">
                  <img class="gallery-image" src="${l}" alt="${r}" />
                </div>
            </a>
            <ul class="gallery-item-info">
                <li class="gallery-item-likes"><b>Likes</b> ${o}</li>
                <li class="gallery-item-views"><b>Views</b> ${q}</li>
                <li class="gallery-item-comments"><b>Comments</b> ${M}</li>
                <li class="gallery-item-downloads"><b>Downloads</b> ${H}</li>
            </ul>
        </li>
        `}).join("")}const y=document.querySelector(".search-input"),m=document.querySelector(".search-btn"),i=document.querySelector(".load-btn"),g=document.querySelector(".in-loader"),p=document.querySelector(".more-loader"),n=document.querySelector("ul.gallery-list");let u=1,w=0;const c=15;let d="",h=0;const T="./img/error.svg",x={titleSize:"16px",maxWidth:432,position:"topRight",closeOnEscape:!0,icon:"error",iconUrl:T,theme:"dark"},S=new O(".gallery-list a",{captionsData:"alt",captionDelay:250});m==null||m.addEventListener("click",async a=>{if(a.preventDefault(),d=(y==null?void 0:y.value.trim())??"",d===""){n.innerHTML="",i.classList.add("visually-hidden");return}n.innerHTML="",g.classList.toggle("visually-hidden"),u=1;try{const{data:e}=await v(d,c,u);if(e.hits.length||i.classList.contains("visually-hidden")||i.classList.add("visually-hidden"),!e.totalHits){n.innerHTML="",g.classList.add("visually-hidden"),f.error({...x,message:"Sorry, there are no images matching your search query. Please try again!"});return}n.insertAdjacentHTML("beforeend",b(e)),g.classList.add("visually-hidden"),i.classList.remove("visually-hidden"),e.totalHits<c&&(i.classList.add("visually-hidden"),f.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})),w=Math.ceil(e.totalHits/c),S.refresh()}catch(e){console.error(e);return}});i.addEventListener("click",async a=>{var e;a.preventDefault(),p.classList.remove("visually-hidden"),i.classList.add("visually-hidden");try{const{data:s}=await v(d,c,++u);n.insertAdjacentHTML("beforeend",b(s)),p.classList.add("visually-hidden"),i.classList.remove("visually-hidden"),S.refresh(),h===0&&(h=((e=document.querySelector(".gallery-item"))==null?void 0:e.getBoundingClientRect().height)??0),window.scrollBy({top:h*2,behavior:"smooth"}),w===u&&(i.classList.add("visually-hidden"),f.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch(s){console.error(s)}});
//# sourceMappingURL=commonHelpers.js.map
